import pika

connection = pika.BlockingConnection(pika.ConnectionParameters('localhost'))
channel = connection.channel()
channel.queue_declare(queue='costplusdrugs')
messages = ["https://costplusdrugs.com/medications/abacavirlamivudine-600mg_300mg-tablet/",
           "https://costplusdrugs.com/medications/acetazolamide-250mg-tablet/",
           "https://costplusdrugs.com/medications/Acyclovir-400mg-Tablet/",
           "https://costplusdrugs.com/medications/albendazole-200mg-tablet/",
           "https://costplusdrugs.com/medications/albuterol-90mcg-inhaler8_5g/",
           "https://costplusdrugs.com/medications/albuterol-90mcg-inhaler18g/",
           "https://costplusdrugs.com/medications/albuterol-90mcg-inhaler6_7g/",
           "https://costplusdrugs.com/medications/AlbuterolSulfate-0_083-Nebulization%20Solution/",
           "https://costplusdrugs.com/medications/alendronate-70mg-tablet4pack/",
           "https://costplusdrugs.com/medications/alfuzosinhcler-10mg-tablet/",
           "https://costplusdrugs.com/medications/abacavirlamivudine-600mg_300mg-tablet/",
           "https://costplusdrugs.com/medications/acetazolamide-250mg-tablet/",
           "https://costplusdrugs.com/medications/Acyclovir-400mg-Tablet/",
           "https://costplusdrugs.com/medications/albendazole-200mg-tablet/",
           "https://costplusdrugs.com/medications/albuterol-90mcg-inhaler8_5g/",
           "https://costplusdrugs.com/medications/albuterol-90mcg-inhaler18g/",
           "https://costplusdrugs.com/medications/albuterol-90mcg-inhaler6_7g/",
           "https://costplusdrugs.com/medications/AlbuterolSulfate-0_083-Nebulization%20Solution/",
           "https://costplusdrugs.com/medications/alendronate-70mg-tablet4pack/",
           "https://costplusdrugs.com/medications/alfuzosinhcler-10mg-tablet/",
           "https://costplusdrugs.com/medications/abacavirlamivudine-600mg_300mg-tablet/",
           "https://costplusdrugs.com/medications/acetazolamide-250mg-tablet/",
           "https://costplusdrugs.com/medications/Acyclovir-400mg-Tablet/",
           "https://costplusdrugs.com/medications/albendazole-200mg-tablet/",
           "https://costplusdrugs.com/medications/albuterol-90mcg-inhaler8_5g/",
           "https://costplusdrugs.com/medications/albuterol-90mcg-inhaler18g/",
           "https://costplusdrugs.com/medications/albuterol-90mcg-inhaler6_7g/",
           "https://costplusdrugs.com/medications/AlbuterolSulfate-0_083-Nebulization%20Solution/",
           "https://costplusdrugs.com/medications/alendronate-70mg-tablet4pack/",
           "https://costplusdrugs.com/medications/alfuzosinhcler-10mg-tablet/",
           "https://costplusdrugs.com/medications/abacavirlamivudine-600mg_300mg-tablet/",
           "https://costplusdrugs.com/medications/acetazolamide-250mg-tablet/",
           "https://costplusdrugs.com/medications/Acyclovir-400mg-Tablet/",
           "https://costplusdrugs.com/medications/albendazole-200mg-tablet/",
           "https://costplusdrugs.com/medications/albuterol-90mcg-inhaler8_5g/",
           "https://costplusdrugs.com/medications/albuterol-90mcg-inhaler18g/",
           "https://costplusdrugs.com/medications/albuterol-90mcg-inhaler6_7g/",
           "https://costplusdrugs.com/medications/AlbuterolSulfate-0_083-Nebulization%20Solution/",
           "https://costplusdrugs.com/medications/alendronate-70mg-tablet4pack/",
           "https://costplusdrugs.com/medications/alfuzosinhcler-10mg-tablet/",
           "https://costplusdrugs.com/medications/abacavirlamivudine-600mg_300mg-tablet/",
           "https://costplusdrugs.com/medications/acetazolamide-250mg-tablet/",
           "https://costplusdrugs.com/medications/Acyclovir-400mg-Tablet/",
           "https://costplusdrugs.com/medications/albendazole-200mg-tablet/",
           "https://costplusdrugs.com/medications/albuterol-90mcg-inhaler8_5g/",
           "https://costplusdrugs.com/medications/albuterol-90mcg-inhaler18g/",
           "https://costplusdrugs.com/medications/albuterol-90mcg-inhaler6_7g/",
           "https://costplusdrugs.com/medications/AlbuterolSulfate-0_083-Nebulization%20Solution/",
           "https://costplusdrugs.com/medications/alendronate-70mg-tablet4pack/",
           "https://costplusdrugs.com/medications/alfuzosinhcler-10mg-tablet/",
           "https://costplusdrugs.com/medications/abacavirlamivudine-600mg_300mg-tablet/",
           "https://costplusdrugs.com/medications/acetazolamide-250mg-tablet/",
           "https://costplusdrugs.com/medications/Acyclovir-400mg-Tablet/",
           "https://costplusdrugs.com/medications/albendazole-200mg-tablet/",
           "https://costplusdrugs.com/medications/albuterol-90mcg-inhaler8_5g/",
           "https://costplusdrugs.com/medications/albuterol-90mcg-inhaler18g/",
           "https://costplusdrugs.com/medications/albuterol-90mcg-inhaler6_7g/",
           "https://costplusdrugs.com/medications/AlbuterolSulfate-0_083-Nebulization%20Solution/",
           "https://costplusdrugs.com/medications/alendronate-70mg-tablet4pack/",
           "https://costplusdrugs.com/medications/alfuzosinhcler-10mg-tablet/",
           "https://costplusdrugs.com/medications/abacavirlamivudine-600mg_300mg-tablet/",
           "https://costplusdrugs.com/medications/acetazolamide-250mg-tablet/",
           "https://costplusdrugs.com/medications/Acyclovir-400mg-Tablet/",
           "https://costplusdrugs.com/medications/albendazole-200mg-tablet/",
           "https://costplusdrugs.com/medications/albuterol-90mcg-inhaler8_5g/",
           "https://costplusdrugs.com/medications/albuterol-90mcg-inhaler18g/",
           "https://costplusdrugs.com/medications/albuterol-90mcg-inhaler6_7g/",
           "https://costplusdrugs.com/medications/AlbuterolSulfate-0_083-Nebulization%20Solution/",
           "https://costplusdrugs.com/medications/alendronate-70mg-tablet4pack/",
           "https://costplusdrugs.com/medications/alfuzosinhcler-10mg-tablet/",
           "https://costplusdrugs.com/medications/abacavirlamivudine-600mg_300mg-tablet/",
           "https://costplusdrugs.com/medications/acetazolamide-250mg-tablet/",
           "https://costplusdrugs.com/medications/Acyclovir-400mg-Tablet/",
           "https://costplusdrugs.com/medications/albendazole-200mg-tablet/",
           "https://costplusdrugs.com/medications/albuterol-90mcg-inhaler8_5g/",
           "https://costplusdrugs.com/medications/albuterol-90mcg-inhaler18g/",
           "https://costplusdrugs.com/medications/albuterol-90mcg-inhaler6_7g/",
           "https://costplusdrugs.com/medications/AlbuterolSulfate-0_083-Nebulization%20Solution/",
           "https://costplusdrugs.com/medications/alendronate-70mg-tablet4pack/",
           "https://costplusdrugs.com/medications/alfuzosinhcler-10mg-tablet/",
           "https://costplusdrugs.com/medications/abacavirlamivudine-600mg_300mg-tablet/",
           "https://costplusdrugs.com/medications/acetazolamide-250mg-tablet/",
           "https://costplusdrugs.com/medications/Acyclovir-400mg-Tablet/",
           "https://costplusdrugs.com/medications/albendazole-200mg-tablet/",
           "https://costplusdrugs.com/medications/albuterol-90mcg-inhaler8_5g/",
           "https://costplusdrugs.com/medications/albuterol-90mcg-inhaler18g/",
           "https://costplusdrugs.com/medications/albuterol-90mcg-inhaler6_7g/",
           "https://costplusdrugs.com/medications/AlbuterolSulfate-0_083-Nebulization%20Solution/",
           "https://costplusdrugs.com/medications/alendronate-70mg-tablet4pack/",
           "https://costplusdrugs.com/medications/alfuzosinhcler-10mg-tablet/",
           "https://costplusdrugs.com/medications/abacavirlamivudine-600mg_300mg-tablet/",
           "https://costplusdrugs.com/medications/acetazolamide-250mg-tablet/",
           "https://costplusdrugs.com/medications/Acyclovir-400mg-Tablet/",
           "https://costplusdrugs.com/medications/albendazole-200mg-tablet/",
           "https://costplusdrugs.com/medications/albuterol-90mcg-inhaler8_5g/",
           "https://costplusdrugs.com/medications/albuterol-90mcg-inhaler18g/",
           "https://costplusdrugs.com/medications/albuterol-90mcg-inhaler6_7g/",
           "https://costplusdrugs.com/medications/AlbuterolSulfate-0_083-Nebulization%20Solution/",
           "https://costplusdrugs.com/medications/alendronate-70mg-tablet4pack/",
           "https://costplusdrugs.com/medications/alfuzosinhcler-10mg-tablet/"]
len_message = len(messages)
# print(len_message)

for i in range(len_message):
	message = messages[i]
# 	print(message)
# print(len(message))
	channel.basic_publish(exchange = '',routing_key = 'costplusdrugs',body = message)
	print(f"Detailed page url: {message}")

connection.close()

